[profile.default]
    src = "contracts"
    out = "out"
    libs = ["lib","node_modules"]
    auto_detect_solc = false
    optimizer = true
    solc = "0.8.3"
    evm_version = "cancun"
    cache_path = 'cache_forge'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
